package ex_the_simpsons;
import _doubly_linked_list.Cell;
import _doubly_linked_list.DoublyLinkedList;
public class Main {
    public static void main(String[] args) {
        DoublyLinkedList myList=new DoublyLinkedList();
        System.out.println("1st operation");
        myList.addEnd("Homer");
        myList.addEnd("Marge");
        Main.showList(myList.getCells());
        System.out.println("\n");
        System.out.println("2nd operation");
        myList.clean();
        Main.showList(myList.getCells());
        System.out.println("\n");
        System.out.println("3rd operation");
        myList.addEnd("Homer");
        myList.addPos(0,"Bart");
        myList.addPos(1,"Moll");
        Main.showList(myList.getCells());
        System.out.println("\n");
        System.out.println("4th operation");
        myList.clean();
        if(myList.isEmpty()) System.out.println("Empty list");
        System.out.println("\n");
        System.out.println("5th operation");
        myList.addEnd("Homer");
        myList.addEnd("Bart");
        myList.addBeginning("Lisa");
        Main.showList(myList.getCells());
        System.out.println("myList has size "+myList.size());
        System.out.println("\n");
        System.out.println("6th operation");
        myList.clean();
        Main.showList(myList.getCells());
        System.out.println("\n");
        System.out.println("7th operation");
        myList.addEnd("Homer");
        myList.addEnd("Maggie");
        myList.addPos(0,"Bart");
        myList.addPos(1,"Marge");
        Main.showList(myList.getCells());
        if(myList.contains("Lisa")) System.out.println("myList contains Lisa");
        else System.out.println("myList doesn't have Lisa");
        System.out.println("\n");
        System.out.println("8th operation");
        myList.clean();
        if(myList.isEmpty()) System.out.println("Empty list");
        System.out.println("\n");
        System.out.println("9th operation");
        myList.addEnd("Homer");
        myList.addEnd("Bart");
        Main.showList(myList.getCells());
        System.out.println("myList has size "+myList.size());
        System.out.println("\n");
        System.out.println("10th operation");
        System.out.println("Does myList have Marge? "+myList.contains("Marge"));
        System.out.println("Does myList have Homer? "+myList.contains("Homer"));
        System.out.println("Does myList have Bart? "+myList.contains("Bart"));
        System.out.println("Does myList have Maggie? "+myList.contains("Maggie"));
        System.out.println("\nmyList has size "+myList.size());
        System.out.println("\n");
        System.out.println("11th operation");
        myList.clean();
        if(myList.isEmpty()) System.out.println("Empty list");
        System.out.println("\n");
        System.out.println("12th operation");
        myList.addBeginning("Homer");
        myList.addBeginning("Bart");
        myList.addEnd("Marge");
        myList.addPos(1,"Maggie");
        myList.addBeginning("Ned Flanders");
        myList.addEnd("Sr. Burns");
        Main.showList(myList.getCells());
        System.out.println("\n");
        System.out.println("13th operation");
        myList.removeLast();
        Main.showList(myList.getCells());
        System.out.println("\n");
        System.out.println("14th operation");
        myList.removePos(1);
        Main.showList(myList.getCells());
        System.out.println("\nmyList has size "+myList.size());
        System.out.println("\n");
        System.out.println("15th operation");
        System.out.println("Does myList have Marge? "+myList.contains("Marge"));
        System.out.println("Does myList have Homer? "+myList.contains("Homer"));
        System.out.println("Does myList have Bart? "+myList.contains("Bart"));
        System.out.println("Does myList have Maggie? "+myList.contains("Maggie"));
        System.out.println("\nmyList has size "+myList.size());
        System.out.println("\n");
        System.out.println("16th operation");
        myList.removeFirst();
        Main.showList(myList.getCells());
        System.out.println("\nmyList has size "+myList.size());
        System.out.println("\n");
        System.out.println("17th operation");
        System.out.println("Does myList have Marge? "+myList.contains("Marge"));
        System.out.println("Does myList have Homer? "+myList.contains("Homer"));
        System.out.println("Does myList have Bart? "+myList.contains("Bart"));
        System.out.println("Does myList have Maggie? "+myList.contains("Maggie"));
        System.out.println("\nmyList has size "+myList.size());
        System.out.println("\n");
        System.out.println("18th operation");
        myList.clean();
        Main.showList(myList.getCells());
    }
    
    private static void showList(Cell[] cells){
        if(cells==null) System.out.println("Empty list");
        else for(Cell throughCells:cells) System.out.println(throughCells.getData());
        System.out.println();
    }
}
